dubbo:
  application:
    name: order-service-consumer
  protocol:
    name: dubbo
    port: -1
    serialization: fastjson2
  registry:
#    address: zookeeper://${zookeeper.address:192.168.0.190}:2181
    address: nacos://192.168.0.190:8848
  consumer:  # 配置消费者都不检查注册中心是否有可用的服务提供者
    check: false
    timeout: 1000 #默认是1000毫秒

spring:
  application:
    name: order-service-consumer
server:
  port: 9993
